name: flutter_app_badger
description: Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
version: 1.5.1
homepage: https://github.com/g123k/flutter_app_badger

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.g123k.flutterappbadger
        pluginClass: FlutterAppBadgerPlugin
      ios:
        pluginClass: FlutterAppBadgerPlugin
      macos:
        pluginClass: FlutterAppBadgerPlugin

