name: flutter_app_badger
description: Launcher App badger
version: 1.0.3
author: Edouard Marquez <moi@edouard-marquez.me>
homepage: https://github.com/g123k/flutter_app_badger

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: fr.g123k.flutterappbadger
    pluginClass: FlutterAppBadgerPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
